#!/bin/bash

# Generated JWT Secret
JWT_SECRET="a52a9f68f4fd4d506820af96f97951d9e715d31fb6f12bb9089cb7dfa3349492"

echo "🚀 Deployment Setup Complete!"
echo "=============================="
echo ""
echo "Your JWT Secret has been generated: $JWT_SECRET"
echo ""
echo "Now run these commands:"
echo ""
echo "=== BACKEND (Railway) ==="
echo "1. railway login"
echo "2. cd src/server"
echo "3. railway init"
echo "4. railway add mysql"
echo "5. railway variables set JWT_SECRET='$JWT_SECRET'"
echo "6. railway variables set ESCROW_CONTRACT_ID='CBQRMSHT6JPJNVHNW4ZQOOWVZKAEVBAJKS3WKGJUUEGFFULYA75444WE'"
echo "7. railway variables set NETWORK_PASSPHRASE='Test SDF Network ; September 2015'"
echo "8. railway up"
echo "9. railway domain  # Copy this URL!"
echo ""
echo "=== DATABASE ==="
echo "10. railway mysql < setup_database.sql"
echo ""
echo "=== FRONTEND (Vercel) ==="
echo "11. cd ../../src/client"
echo "12. vercel login"
echo "13. vercel env add REACT_APP_API_URL production"
echo "    (Enter your Railway backend URL from step 9)"
echo "14. vercel --prod"
echo ""
echo "=== UPDATE CORS ==="
echo "15. cd ../server"
echo "16. railway variables set CORS_ORIGIN='https://your-app.vercel.app'"
echo "17. railway restart"
echo ""
echo "DONE! 🎉"

